baseURL = 'https://fabschools.netlify.app'
languageCode = 'en-us'
title = 'Fabschools.pt'
theme = "aster"
resourceDir = "resources"
paginate = 4
summaryLength = 20
DefaultContentLanguage = "en"

# Menu Settings
[menu]
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
  
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  identifier = "PostgraduateCourse"
  name = "Postgraduate Studies"
  url = "/pgdpie/"
  weight = 3
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 4
[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 5

# Main Settings
[params]
dateFormat = "January 2, 2006"
authorName = "Fabschools"
disqusComments = "test" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "https://formspree.io/f/xdornreq" #YOUR FORMSPREE URL
googleAnalytics = "G-GN0NB9HJWR" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[params.preloader]
logo = "images/logo.png"

# Header Settings
[params.header]
logo = "images/logo.png"

# Footer Settings
[params.footer]
copyright = "CC-BY 2023 ESELx - IPL"
col1_title = "Address:"
col1_text = "Escola Superior de Educação de Lisboa<br/>Campus de Benfica do IPL<br/>1549-003 Lisboa"
col2_title = "Follow Us:"
col2_text = ""
col3_title = "Get in touch:"
col3_text = "fabschools@eselx.ipl.pt<br/>(+351) 217 115 500"

# Social Settings
[[params.social]]
title = "Instagram"
icon = "fab fa-twitter"
url = "https://www.twitter.com/"
weight = 1
[[params.social]]
title = "Twitter"
icon = "fab fa-twitter"
url = "https://www.twitter.com/"
weight = 1
[[params.social]]
title = "Dribbble"
icon = "fab fa-dribbble"
url = "https://www.dribbble.com/"
weight = 2
[[params.social]]
title = "Behance"
icon = "fab fa-behance"
url = "https://www.behance.net/"
weight = 3

# Sidebar
[params.sidebar]
enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]

# Portfolio Settings
[params.portfolio]
homeNumOfItems = 12
[[params.portfolio.filters]]
name = "Construction"
slug = "construction"
[[params.portfolio.filters]]
name = "Robotics"
slug = "robotics"
[[params.portfolio.filters]]
name = "Game"
slug = "game"
[[params.portfolio.filters]]
name = "other creative Artefacts"
slug = "other"

# Sitemap Settings
[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

